version: "3.7"

services:
  api:
    build: ./English2Arabic-Belt3/api
    environment:
      - CONNECTION_STRING=demo://demo_user:demo_user@db/demo_db
    depends_on: 
      - db 
    volumes:
      - ./api:/app
    networks:
      - public
      - private  

  web:
    build: ./English2Arabic-Belt3/web
    environment:
      - API_URL=http://api:3001/data
    depends_on:
      - api
    ports:
      - "3000:80"
    networks:
      - public
      

  db:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_user
      POSTGRES_DB: demo_db
    volumes:
      - ./init_sql_scripts/:/docker-entrypoint-initdb.d
    networks:
      - private 

networks:
 public:
 private: